### ISSUE TITLE
todo list before release of 1.3.5

### ISSUE THREAD

**Issue by asl97** [nhammond129/ch.py#33]
- [x] rename internal functions
- [x] add proper docstrings for public functions
- [x] finish issue https://github.com/Nullspeaker/ch.py/issues/28
- [x] make an official release and a new branch for [1.3.5](https://github.com/Nullspeaker/ch.py/tree/1.3.5)
- [x] using efficient threading for non-blocking joining https://github.com/Nullspeaker/ch.py/issues/30 (might be backward incomparable)

other lib already using threading but i am worry about the performance of thread,
it really sucks when there more thread than core so i ain't going to do what chlib.py do,
but one extra thread shouldn't be so bad, at best, maybe a 10% for first extra thread
and 1% for each other thread lost of performance in exchange of a perfect,
non-blocking joining

but most computer nowadays all have at least a duo core, but i think it wouldn't work so well with my psp and other single core device, so i be recommending 1.3.5 once it's out for those single core.

in any case, this is a todo list.
